spring:
  servlet:
    multipart:
      max-request-size:
        10MB
      max-file-size:
        10MB
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  datasource:
    url: jdbc:h2:mem:codereview
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
  config:
    import: "optional:classpath:application-secrets.yaml"
  application:
    name: git-bro
  security:
    user:
      name: user
      password: password

#Never commit this code! If you do, navigate to hugging face and generate a new token.
huggingface:
    api:
        token: hf_iK3232323cXdqxWoQuUVep24323
openai:
    api:
        token: sk-proj-QGI7z17KoSTg234234234234hlwekjh5234kjh23lk4hj23lkj4h23lkjh44z44eETnfYbCVvHj3U8iNL4A

app:
  ai-provider: chatgpt
  feedback:
    file-path: ${FEEDBACK_FILE_PATH:/Users/erikmikac/code-review-feedback.txt}
server:
  port: 8080
